language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - PHPUNIT_FLAGS="-v"

matrix:
    fast_finish: true
    include:
      # Test the latest stable release
      - php: 7.4
        env:
            - COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
            - XDEBUG_MODE="coverage"

      # Latest commit to master
      - php: 7.4
        env:
            - STABILITY="dev" COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
            - XDEBUG_MODE="coverage"

      - php: 8.0
        env:
          - STABILITY="dev" COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
          - XDEBUG_MODE="coverage"

    allow_failures:
        # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/phpunit $PHPUNIT_FLAGS
